# Generated by Django 4.1.7 on 2023-02-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
